Expenses swagger documentation
s0vit/shoplist-be pull request #66
Opened 2024-05-31 22:06 UTC by ipavka

#65 Expenses swagger documentation, in the process...

2024-05-31 22:41 UTC, itbali approved these changes

2024-05-31 22:41 UTC, itbali commented on src/category/decorators/get-category-swagger-decorator.ts
> +    ApiCookieAuth('accessToken'),
accessToken is not required here, swagger will automatically get it

2024-05-31 22:55 UTC, itbali requested changes
check in progress

2024-05-31 23:02 UTC, itbali commented on src/expenses/decorators/get-expenses-sw-dec.ts
> +      description: 'The users Expenses successfully received.',
please, add type here and array option, so it will finally look like:
`    ApiResponse({
      status: 200,
      description: 'The users Expenses successfully received.',
      type: ExpensesResponseDto,
      isArray: true,
    }),
`

![CleanShot 2024-06-01 at 00 59 38](https://github.com/s0vit/shoplist-be/assets/89312941/500e3d28-a16e-43a6-b934-2497e51728f5)

2024-05-31 23:02 UTC, itbali commented on src/expenses/dto/expenses-input.dto.ts
> +    description: 'Comments for the expense',
same here 
      type: ExpensesResponseDto,

2024-05-31 23:03 UTC, itbali commented on src/category/decorators/get-category-swagger-decorator.ts
>        description: 'The users categories successfully received.',
btw it will be great to add here:
      type: ExpensesResponseDto,

2024-06-01 12:57 UTC, ipavka commented on src/expenses/decorators/get-expenses-sw-dec.ts
> +      description: 'The users Expenses successfully received.',
I know, in the progress

2024-06-01 14:29 UTC, itbali approved these changes

2024-06-01 14:31 UTC, merged